name: Daily Tech Digest

on:
  schedule:
    - cron: "0 3 * * *"   # 03:00 UTC = 07:00 Asia/Tbilisi
  workflow_dispatch:       # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate digest
        env:
          DIGEST_TZ: "Asia/Tbilisi"
        run: |
          python daily_tech_digest.py --out digest.md --hours 24 --max-per-cat 7

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add digest.md
          git commit -m "Daily digest $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
